version: "3.9"

services:
  backend:
    build:
      context: ./server
    container_name: backend
    ports:
      - "8080:8080"
    env_file:
      - ./server/.env
    dns:
      - 8.8.8.8
      - 8.8.4.4
    networks:
      - app-network

  frontend:
    build:
      context: ./client
    container_name: frontend
    ports:
      - "8000:80"
    environment:
      - VITE_API_BASE_URL=http://backend:8080
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
# docker-compose -p airbnb up -d
